services:
  bot:
    build:
      context: ./
    tty: true
    stdin_open: true
    volumes:
      - ./:/bot
    depends_on:
      - task-manager
    env_file:
      - .env
    command: >
      sh -c "poetry run python app.py"

  task-manager:
    image: zhukata/django_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1  # Отключение буферизации
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"